adding Edge type
Code-Republic-Community/graphviz pull request #13
Opened 2023-04-15 11:01 UTC by Sveta-1999

This PR closes [GV-10](https://graphviz.atlassian.net/browse/GV-10?atlOrigin=eyJpIjoiNzQzMjA5YTQ1OTY5NGEyMGI1ZjBjYTAyMzAzODQ1ZjgiLCJwIjoiaiJ9) ticket.
Added methods getter, setter which is the initialization of member data's.

2023-04-15 14:39 UTC, aramhovakimyan commented on examples/golden_graph/edge.hpp
Lets change header guards name like this:
EDGE_CLASS -> EXAMPLES_GOLDEN_GRAPH_EDGE_HPP

2023-04-17 11:12 UTC, SarkisKhachatryan requested changes

2023-04-17 11:12 UTC, SarkisKhachatryan commented on examples/golden_graph/edge.hpp
> +    Edge(int id_1, int id_2) : _id_1(id_1), _id_2(id_2) {}
move to cpp

2023-04-17 11:12 UTC, SarkisKhachatryan commented on examples/golden_graph/edge.hpp
> +    void set_id_1(int);
add argument names

2023-04-17 11:12 UTC, SarkisKhachatryan commented on examples/golden_graph/edge.cpp
> +
remove redundant line

2023-04-19 13:05 UTC, SarkisKhachatryan submitted a review, later dismissed

2023-04-19 13:13 UTC, SarkisKhachatryan approved these changes

2023-04-19 13:13 UTC, merged