GV-8 : add node class and its implementation
Code-Republic-Community/graphviz pull request #9
Opened 2023-04-15 10:37 UTC by ArsenShmavonyan

GV-8 closed this ticket [](url)https://graphviz.atlassian.net/browse/GV-8?atlOrigin=eyJpIjoiZjEyNThiYmIyM2E3NDhkN2I3MmZmMzA1NjYyZGRhNTMiLCJwIjoiaiJ9

2023-04-15 12:45 UTC, aramhovakimyan commented on examples/golden_graph/Node.h
Lets change header guards names letters in uppercase.
Node_h -> NODE_HPP
And change file extension in .hpp

2023-04-17 11:02 UTC, Sveta-1999 reviewed
Please change member data for example m_id etc., and change the function names Camal case, and change "edge.hpp"

2023-04-17 11:02 UTC, SarkisKhachatryan requested changes

2023-04-17 11:02 UTC, SarkisKhachatryan commented on examples/golden_graph/Node.h
> +#include "Edge.h"
includes should be of the following form:
our headers
third_party
stl

2023-04-19 13:28 UTC, merged